# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qo4-BMDAwDfh3_Z5wMXxVoozFnRorOWW
"""

import matplotlib.pyplot as plt
import numpy as np

# make the data
 np.random.seed(3)
  x = 4 + np.random.normal(0, 2, 24)
  y = 4 + np.random.normal(0, 2, len(x))

# size and color:

sizes = np.random.uniform (15, 80, len(x))
 colors = np.random.uniform (15, 80, len(x))

# plot

fig, ax = plt.subplots()

ax.scatter(x, y, s=sizes, c=colors, vmin=0, vmax=100)

ax.set(xlim=(0, 8), xticks=np.arange(1, 8), ylim=(0, 8), yticks=np.arange(1, 8))

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# make the data
np.random.seed(3)
x = 4 + np.random.normal(0, 2, 24)
y = 4 + np.random.normal(0, 2, len(x))

# size and color:
sizes = np.random.uniform(15, 80, len(x))
colors = np.random.uniform(15, 80, len(x))

# plot
fig, ax = plt.subplots()

ax.scatter(x, y, s=sizes, c=colors, vmin=0, vmax=100)

ax.set(xlim=(0, 8), xticks=np.arange(1, 8), ylim=(0, 8), yticks=np.arange(1, 8))

plt.show()

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.plot(x, y)
plt.title('Sinus Funktsiyasi Grafiki')
plt.xlabel('X qiymatlari')
plt.ylabel('Sin(X)')
plt.show()

!pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread( "rasam.jpg")
cv2_imshow(rasm)

oqqora= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread( "rasm .jpg")
cv2_imshow(rasm)

oqqora= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread( "crasam.jpg")
cv2_imshow(rasm)

oqqora= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

import pandas as pd
# Yuklangan fayl nomini o'zgartiring
df = pd.read_csv('WHO COVID-19 cases.csv')
print(df)

filtered_df = df[df['Country'] == 'Afghanistan']
print(len(filtered_df))

filtered_df = df[df['Continent'] == 'Asia']
print(len(filtered_df))

filtered_df = df[df['Continent'] == 'North America']
print(len(filtered_df))

filtered_df = df[df['Country_code'] == 'AU']
print(len(filtered_df))

filtered_df = df[df['Continent'] == 'Europe']
print(len(filtered_df))

filtered_df = df[df['Country_code'] == 'AF']
print(len(filtered_df))